src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $subtitle = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $illustration = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration_title = null;

    #[ORM\Column(length: 255)]
    private ?string $icon_link = null;

    #[ORM\Column(length: 255)]
    private ?string $author_icon = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    #[ORM\Column(length: 255)]
    private ?string $icon_category = null;

    #[ORM\Column(length: 255)]
    private ?string $admin = null;

    #[ORM\Column(length: 255)]
    private ?string $adminIcon = null;

    #[ORM\Column(length: 255)]
    private ?string $message = null;

    #[ORM\Column(length: 255)]
    private ?string $messageIcon = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): static
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): static
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getIllustrationTitle(): ?string
    {
        return $this->illustration_title;
    }

    public function setIllustrationTitle(string $illustration_title): static
    {
        $this->illustration_title = $illustration_title;

        return $this;
    }

    public function getIconLink(): ?string
    {
        return $this->icon_link;
    }

    public function setIconLink(string $icon_link): static
    {
        $this->icon_link = $icon_link;

        return $this;
    }

    public function getAuthorIcon(): ?string
    {
        return $this->author_icon;
    }

    public function setAuthorIcon(string $author_icon): static
    {
        $this->author_icon = $author_icon;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getIconCategory(): ?string
    {
        return $this->icon_category;
    }

    public function setIconCategory(string $icon_category): static
    {
        $this->icon_category = $icon_category;

        return $this;
    }

    public function getAdmin(): ?string
    {
        return $this->admin;
    }

    public function setAdmin(string $admin): static
    {
        $this->admin = $admin;

        return $this;
    }

    public function getAdminIcon(): ?string
    {
        return $this->adminIcon;
    }

    public function setAdminIcon(string $adminIcon): static
    {
        $this->adminIcon = $adminIcon;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getMessageIcon(): ?string
    {
        return $this->messageIcon;
    }

    public function setMessageIcon(string $messageIcon): static
    {
        $this->messageIcon = $messageIcon;

        return $this;
    }
}

templates/includes/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AboutController!
{% endblock %}

{% block body %}
	<section class="en-direct" id="about">
		<div class="container-fluid border-top">
			<div class="row">
				<div class="col pe-md-4">
					<img src="uploads/{{ about.illustration }}" alt="A propos">
				</div>
				<div class="col pe-md-4">
					<div class="mt-2">
						<p class="fw-bolder">{{ about.title }}</p>
						<div>
							<h2>{{ about.subtitle }}</h2>
							<p>{{ about.description }}</p>
						</div>
					</div>
					<div class="row">
						{% for item in aboutDetails %}
							<div class="col-md-6">
								<div class="flaticon1">
									<i class="{{ item.icon }}"></i>
								</div>
								<h3>{{ item.title }}</h3>
								<p>{{ item.subtitle }}</p>
							</div>
						{% endfor %}
					</div>
					<div class="row">
						<div class="col">
							<button id="podcast" class="mt-3">Apprendre encore plus</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/includes/blog.html.twig
<section>
	<div class="securite">
		<p class="fw-bolder">BLOG RÉCENT</p>
		<H2>DERNIÈRES NOUVEAUTÉS DE NOTRE BLOG</H2>
	</div>
	<div class="container">
		<div class="row">
			{% for item in blog %}
				<div class="col-md-4 py-4">
					<div class="card">
						<img src="uploads/{{ item.illustration }}" class="card-img-top img-fluid" alt="Service">
						<h5 class="card-title bg-dark text-white text-center">{{ item.illustrationTitle }}<span>
								<i class="{{ item.iconLink }}"></i>
							</span>
						</h5>
						<div class="admin">
							<i class="{{ item.iconCategory }}"></i>
							<p>{{ item.category }}</p>
							<i class="{{ item.adminIcon }}"></i>
							<p>{{ item.admin }}</p>
							<i class="{{ item.messageIcon }}"></i>
							<p>{{ item.message }}</p>
						</div>
						<p class="card-text">{{ item.authorIcon }}.</p>
					</div>
				</div>
			{% endfor %}
		</div>
	</section>

templates/includes/carousel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CarouselController!{% endblock %}

{% block body %}
<main>
        <!-- BACKGROUND IMAGE-->
        <section class="position-relative">
            <nav class="z-2 navbar navbar-expand-lg navbar-expand-md navbar-expand-sm bg-transparent position-absolute top-0 start-50 translate-middle"
                id="nav-padding">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse">
                        <div class="navbar-nav ms-auto">
                            <a class="nav-link" <a href="{{ path ('app_home')}}" id="nav-orange">Accueil</a>
                            <a class="nav-link text-white" href="#about">À propos</a>
                            <a class="nav-link text-white" href="#service">Prestations de service</a>
                            <a class="nav-link text-white" href="#personnel">Gardes</a>
                            <div>
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Pages
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item bg-transparent text-black" href="#">La page</a></li>
                                    <li><a class="dropdown-item bg-transparent text-black" href="#">Suivre</a></li>
                                    <li><a class="dropdown-item bg-transparent text-black" href="#">Option</a></li>
                                </ul>
                            </div>
                            <a class="nav-link text-white" href="#footer">Contact</a>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="z-0 carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for item in caroussel %}
                        <div class="{{ item.title }}" data-bs-interval="3000">
                            <img src="uploads/{{ item.image }}" class="d-block w-100" alt="{{ item.description }}">
                        </div>
                        <div class="z-1 position-absolute top-0 start-50 translate-middle" id="slogan">
                            <p class="p-orange fw-bold">VOTRE SÉCURITÉ, NOS EFFORTS</p>
                            <h1 style="color: #ffffff">GARDES HAUTEMENT QUALIFIÉS</h1>
                            <button type="button" class="bg-orange fw-bold">Apprendre encore plus</button>
                        </div>
                    {% endfor %}
                </div>
                {# <button class="carousel-control-prev" type="button" data-bs-target="#carouselHead" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselHead" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button> #}
            </div>
        </section>
{% endblock %}

templates/includes/certification.html.twig
<section class="row pt-5">
	{% for item in certification %}
		<div class="col-md-4 mb-4">
			<div class="d-flex border-end">
				<div class="flaticon1">
					<i class="{{ item.icon }}"></i>
				</div>
				<div class="p-4">
					<h4>{{ item.title }}</h4>
					<p>{{ item.description | raw}}</p>
				</div>
			</div>
		</div>
	{% endfor %}
</section>

templates/includes/footer.html.twig
<footer class="bg-dark py-4" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <img src="uploads/{{ infoFooter.logoFooter }}" alt="footer" class="img-fluid">
                    <p class="text-white mt-3">{{ infoFooter.content }}</p>
                </div>
                <div class="col-lg-2 col-md-4 mt-4 mt-lg-0">
                    <p class="fw-bold text-white">LIENS RAPIDES</p>
                    <ul class="list-unstyled">
                        <li><i class="fa-solid fa-angle-right"></i> Maison</li>
                        <li><i class="fa-solid fa-angle-right"></i> A propos de nous</li>
                        <li><i class="fa-solid fa-angle-right"></i> Nos services</li>
                        <li><i class="fa-solid fa-angle-right"></i> Notre équipe</li>
                        <li><i class="fa-solid fa-angle-right"></i> Contactez-nous</li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-4 mt-4 mt-lg-0">
                    <p class="fw-bold text-white">LIENS RAPIDES</p>
                    <ul class="list-unstyled">
                        <li><i class="fa-solid fa-angle-right"></i> Maison</li>
                        <li><i class="fa-solid fa-angle-right"></i> A propos de nous</li>
                        <li><i class="fa-solid fa-angle-right"></i> Nos services</li>
                        <li><i class="fa-solid fa-angle-right"></i> Notre équipe</li>
                        <li><i class="fa-solid fa-angle-right"></i> Contactez-nous</li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-4 mt-4 mt-lg-0">
                    <div>
                        <p class="fw-bold text-white">ENTRE EN CONTACT</p>
                        <ul class="list-unstyled">
                        {% for item in infoContact %}
                            <li><i class="fa-solid fa-location-dot"></i> {{ item.description }}</li>                      
                        {% endfor %}
                        </ul>
                    </div>
                    <div class="icon d-flex">
                        <a href="#" class="text-white me-2"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" class="text-white me-2"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="text-white me-2"><i class="fab fa-linkedin"></i></a>
                        <a href="#" class="text-white me-2"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <hr class="bg-white mt-4">
            <div class="row">
                <div class="col-lg-12">
                    <nav class="navbar navbar-dark bg-dark">
                        <div class="container">
                            <p class="text-white mb-0"><i class="fa-regular fa-copyright"></i> <strong>Nom de votre
                                    site.</strong> Tous droits réservés. Conçu par <strong>HTML Codex</strong></p>
                            <div class="text-white d-flex">
                                <p class="me-4">Confidentialité</p>
                                <p class="me-4">Termes</p>
                                <p class="me-4">FAQ</p>
                                <p class="me-4">Aide</p>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </footer>

templates/includes/infoscontact.html.twig
<header>
	<div class="bg-dark">
		<div class="container-fluid m-3 d-flex justify-content-between p-1">
			<p class="text-white mb-0 mx-5">Horaires d'ouvertures: 8h - 21h00</p>
			<div class="mx-5">
				<a href="#" class="text-light m-2 text-decoration-none">Suivez-nous:</a>
				<a href="#" class="text-light m-2"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="text-light m-2"><i class="fab fa-twitter"></i></a>
				<a href="#" class="text-light m-2"><i class="fab fa-linkedin"></i></a>
				<a href="#" class="text-light m-2"><i class="fab fa-instagram"></i></a>
				<a href="#" class="text-light m-2"><i class="fab fa-youtube"></i></a>
			</div>
		</div>
	</div>
	<div class="d-flex justify-content-between flex-wrap mx-3">
		<img src="uploads/{{ infoLogo.illustration }}" alt="Logo">
		<div class="d-flex">
			{% for item in infoContact %}
				<div class="text-center border-end mb-3 me-3">
					<a class="text-decoration-none" style="color: black;" href="#">{{ item.title }}</a>
					<p style="color: grey;">{{ item.description }}</p>
				</div>
			{% endfor %}
		</div>
	</header>

templates/includes/newsletter.html.twig
<section>
	<div class="container-fluid bg-rouge text-center position-relative">
		<h2 class="text-white font-weight-bold mt-5 mb-3">ABONNEZ-VOUS A NOTRE NEWSLETTER</h2>
		<p class="text-white mb-4">Abonnez-vous et recevez notre dernier article dans votre boîte de réception</p>
    <div class="d-flex justify-content-center">
			{{ form(form) }}
		</div>
	</div>
</section>

templates/includes/personnel.html.twig
<section id="personnel">
	<div class="securite">
		<p class="fw-bolder">AGENTS DE SECURITÉ</p>
		<h2>RENCONTREZ NOS AGENTS DE SECURITÉ</h2>
	</div>
	<div class="container text-center">
        <div class="row mb-5">
            {% for agent in personnel %}  {# il y a 4 elements dans la collection, on commence a compter par 1 #}
                {% if loop.index % 2 == 0 %}  {# loop = 1, 1 est impair donc ce bloc ne s'execute pas au premier tour mais il va le faire en ligne 38 #}
                <div class="col">
                    <img class="miniature" src="uploads/{{ agent.image }}" alt="officer">
                </div>
                {% endif %}
                {% if loop.index % 2 == 1 %}
                    <div class="col text-end mt-5">
                {% else %}
                    <div class="col text-start mt-5">
                {% endif %}           
                        <h5>{{ agent.officer_name }}</h5>
                        <h6>{{ agent.designation }}</h6>
                        <p>{{ agent.description }}</p>
                        <div class="social">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                {% if loop.index % 2 == 1 %}  {# 1 est impair donc le code s'execute #}
                <div class="col">
                    <img class="miniature" src="uploads/{{ agent.image }}" alt="officer">
                </div>
                {% endif %}

                {% if loop.index == 2 %}
                    </div><div class="row mb-5">
                {% endif %}
            {% endfor %}
        </div>
    </div>
</section>

templates/includes/service.html.twig
<section class="mt-5" id="service">
	<div class="securite">
		<p class="fw-bolder">NOS SERVICES</p>
		<h2 class="titre">SERVICES DE SECURIT&Eacute HAUT DE GAMME</h2>
	</div>
	<div class="container security">
		<div class="row">
			{% for item in service %}
				<div class="col-md-6 col-lg-4 mb-4 pb-3">
					<div class="card mb-2 p-3">
						<img class="card-img-top" src="uploads/{{ item.illustration }}" alt="Logo">
						<div class="card-body bg-dark d-flex align-items-center p-0">
							<h3 class="{{ item.title }} font-weight-normal d-flex flex-shrink-0 align-items-center justify-content-center text-white m-0 mr-3" style="width: 45px; height: 45px; background: #e45f4e;"></h3>
							<h5 class="card-title text-white text-truncate m-0">{{ item.subtitle }}</h5>
						</div>
						<div class="card-footer">{{ item.description }}</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</section>

templates/includes/statistic.html.twig
<section class="container-fluid">
	<div class="d-flex" id="statistics">
		{% for item in statistic %}
			<div>
				<i class="{{ item.icon }}"></i>
				<h2 class="text-center">{{ item.value }}</h2>
				<p>{{ item.category }}</p>
			</div>
		{% endfor %}
	</div>
</section>

templates/includes/testimonial.html.twig
<section class="bg-light">
	<div class="securite">
		<p class="fw-bolder">TÉMOIGNAGE</p>
		<h2>CE QUE DISENT NOS CLIENT</h2>
	</div>
	<div class="container">
		<div class="row p-5 mb-4">
			{% for item in testimonial %}
				<div class="col">
					<div class="col border p-4 bg-white bubble mb-5">
						<p>{{ item.content }}</p>
					</div>
					<div class="col">
						<div class="image">
							<img class="card-img-top" src="uploads/{{ item.image }}" alt="testimonial">
						</div>
						<div>
							<h5>
								<span>{{item.authorName}}</span>
							</h5>
							<P>{{item.poste}}</P>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</section>

templates/includes/whyChooseUs.html.twig
<section class="container mb-5">
	<div class="row mt-5">
		<div class="col pe-md-4">
			<div class="my-2">
				<p class="fw-bolder">{{ whyDetails.title }}</p>
				<h2>{{ whyDetails.subtitle }}</h2>
				<img src="uploads/{{ whyDetails.illustration }}" alt="futur">
				<div class="text-under-image">
					<p class="">{{ whyDetails.description }}</p>
					</p>
					<h5 id="pod">Apprendre encore plus</h5>
				</div>
			</div>
		</div>
		<div class="col pe-md-4 d-flex">
			<div class="row">
				{% for item in whyChooseUs %}
					{% if loop.index % 3 == 1 %} {#  chaque troisième élément de la boucle crée une nouvelle colonne. #}
								</div><div class="col">
					{% endif %}
					<div class="m-2">
							<div class="d-flex">
									<div class="flaticon2">
											<i class="{{ item.icon }}"></i>
									</div>
									<div class="ms-2">
											<h4>{{ item.category }}</h4>
											<p>{{ item.description }}</p>
									</div>
							</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	</section>